In [1]:
print("Hello world")

Hello world


In [2]:
import numpy as np

In [3]:
number = np.nan

In [4]:
print(number)

nan


In [5]:
import random
nums = np.random.rand(10)
print(nums)

[0.70004981 0.4763518  0.20832515 0.04713871 0.12643421 0.04176415
 0.45401254 0.26973453 0.23824517 0.2864133 ]


In [6]:
import pandas as pd

In [7]:
data = {"Names":["Monicah","Ann","Faith"],
        "Ages":[21,45,67]}

In [8]:
df = pd.DataFrame(data)
df

Names  Ages
0  Monicah    21
1      Ann    45
2    Faith    67

In [9]:
df.loc[0,'Ages']

21

In [10]:
df['Ages'].sum()

133

In [11]:
df.sort_values(by=("Names"),ascending=True)

Names  Ages
1      Ann    45
2    Faith    67
0  Monicah    21

In [12]:
df = pd.DataFrame({'grps': list('aaabbcaabcccbbc'), 
                   'vals': [12,345,3,1,45,14,4,52,54,23,235,21,57,3,87]})
df

grps  vals
0     a    12
1     a   345
2     a     3
3     b     1
4     b    45
5     c    14
6     a     4
7     a    52
8     b    54
9     c    23
10    c   235
11    c    21
12    b    57
13    b     3
14    c    87

In [13]:
df.groupby('grps')['vals'].max()

grps
a    345
b     57
c    235
Name: vals, dtype: int64

In [14]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [15]:
zeros = np.zeros(5)
print(zeros)

[0. 0. 0. 0. 0.]


In [16]:
ones = np.ones(5)
print(ones)

[1. 1. 1. 1. 1.]


In [17]:
rand_nums = np.random.rand(5)
rand_nums

array([0.96897774, 0.4102273 , 0.72964515, 0.67284954, 0.57534332])

In [18]:
range_arr = np.arange(1,20)
print(range_arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [19]:
linspace_arr = np.linspace(0,50,5)
linspace_arr

array([ 0. , 12.5, 25. , 37.5, 50. ])

In [20]:
reshaped_arr = np.arange(9).reshape(3,3)
reshaped_arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [21]:
arr.size

5

In [22]:
print(reshaped_arr.size)

9


In [23]:
print(reshaped_arr.shape)

(3, 3)


In [24]:
print(arr.dtype)

int32


In [25]:
float_arr = reshaped_arr.astype(float)
print(float_arr)

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


In [26]:
reshaped_arr.max()

8

In [27]:
reshaped_arr.min()

0

In [28]:
print(arr)
arr.sum()

[1 2 3 4 5]


15

In [29]:
arr.mean()

3.0

In [30]:
np.median(arr)

3.0

In [31]:
np.std(arr)

1.4142135623730951

In [32]:
np.var(arr)

2.0

In [33]:
arr.argmax()

4

In [34]:
arr.argmin()

0

In [35]:
sorted_array = np.array([3,1,2,5,4])
print("not sorted",sorted_array)
print("sorted array",np.sort(sorted_array))

not sorted [3 1 2 5 4]
sorted array [1 2 3 4 5]


In [36]:
print(arr[::-1])

[5 4 3 2 1]


In [37]:
unique_arr = np.array([1,2,2,3,3])
result = np.unique(unique_arr)
print(result)

[1 2 3]


In [38]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(np.vstack((arr1,arr2)))


[[1 2 3]
 [4 5 6]]


In [39]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(np.hstack((arr1,arr2)))

[1 2 3 4 5 6]


In [40]:
split_array = np.array([1,2,3,4,5,6])
print(np.split(split_array,2))

[array([1, 2, 3]), array([4, 5, 6])]


In [41]:
identity_matrix = np.eye(8)
print(identity_matrix)

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


In [42]:
rand_ints = np.random.randint(1,10)
print(rand_ints)

6


In [43]:
rand_ints = np.random.randint(1,10,(3,3))
print(rand_ints)

[[6 5 4]
 [7 3 6]
 [6 8 8]]


In [44]:
print(np.diag(rand_ints))

[6 3 8]


In [45]:
print(rand_ints.T)

[[6 7 6]
 [5 3 8]
 [4 6 8]]


In [46]:
print(rand_ints.flatten())

[6 5 4 7 3 6 6 8 8]


In [47]:
filtered_arr = rand_ints[rand_ints>5]
print(filtered_arr)

[6 7 6 6 8 8]


In [48]:
filtered_arr[filtered_arr>8]=10
print(filtered_arr)

[6 7 6 6 8 8]


In [49]:
print(arr1)
print(arr2)

[1 2 3]
[4 5 6]


In [50]:
print(arr1+arr2)

[5 7 9]


In [51]:
print(arr1*arr2)

[ 4 10 18]


In [52]:
print(arr1-arr2)

[-3 -3 -3]


In [53]:
print(arr2/arr1)

[4.  2.5 2. ]


In [54]:
print(np.dot(arr1,arr2))

32


In [55]:
mask = arr1>1
print(mask)

[False  True  True]


In [56]:
print(arr)
print(np.clip(arr,2,4))

[1 2 3 4 5]
[2 2 3 4 4]


In [57]:
print(np.isnan(arr))

[False False False False False]


In [58]:
nan_array = np.array([0,np.nan,8,9, np.nan])
nan_array

array([ 0., nan,  8.,  9., nan])

In [59]:
nan_array[np.isnan(nan_array)] = 0
nan_array

array([0., 0., 8., 9., 0.])

In [60]:
print(np.cumsum(nan_array))

[ 0.  0.  8. 17. 17.]


In [61]:
print(np.cumprod(nan_array))

[0. 0. 0. 0. 0.]


In [62]:
import pandas as pd

In [63]:
df = pd.DataFrame({
    "A":[1,2,3],
    "B":[4,5,6],
    "C":[7,8,9],
    
})
df

A  B  C
0  1  4  7
1  2  5  8
2  3  6  9

In [64]:
df.to_csv("output.csv")

In [65]:
df.head()

A  B  C
0  1  4  7
1  2  5  8
2  3  6  9

In [66]:
df.tail(1)

A  B  C
2  3  6  9

In [67]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 204.0 bytes


In [68]:
df.describe()

A    B    C
count  3.0  3.0  3.0
mean   2.0  5.0  8.0
std    1.0  1.0  1.0
min    1.0  4.0  7.0
25%    1.5  4.5  7.5
50%    2.0  5.0  8.0
75%    2.5  5.5  8.5
max    3.0  6.0  9.0

In [69]:
df['A']

0    1
1    2
2    3
Name: A, dtype: int64

In [70]:
df[['A','B','C']]

A  B  C
0  1  4  7
1  2  5  8
2  3  6  9

In [71]:
df.loc[0]

A    1
B    4
C    7
Name: 0, dtype: int64

In [72]:
df.loc[:,'A']

0    1
1    2
2    3
Name: A, dtype: int64

In [73]:
df.iloc[0]

A    1
B    4
C    7
Name: 0, dtype: int64

In [74]:
df[df['A']>1]

A  B  C
1  2  5  8
2  3  6  9

In [75]:
df['D'] = df['A']+df['B']
df

A  B  C  D
0  1  4  7  5
1  2  5  8  7
2  3  6  9  9

In [76]:
print(df)

   A  B  C  D
0  1  4  7  5
1  2  5  8  7
2  3  6  9  9


In [77]:
df.drop(columns=['D'],inplace=True)
df

A  B  C
0  1  4  7
1  2  5  8
2  3  6  9

In [78]:
df.drop(index=0)
df

A  B  C
0  1  4  7
1  2  5  8
2  3  6  9

In [79]:
df.reset_index(drop=False)

index  A  B  C
0      0  1  4  7
1      1  2  5  8
2      2  3  6  9

In [80]:
df

A  B  C
0  1  4  7
1  2  5  8
2  3  6  9

In [81]:
df.rename(columns={"A":"Alpha"},inplace=True)
df

Alpha  B  C
0      1  4  7
1      2  5  8
2      3  6  9

In [82]:
df.isnull().sum()

Alpha    0
B        0
C        0
dtype: int64

In [83]:
df.fillna(0,inplace=True)

In [84]:
df.dropna(inplace=True)

In [85]:
df.replace(1,100,inplace=True)

In [86]:
df

Alpha  B  C
0    100  4  7
1      2  5  8
2      3  6  9

In [87]:
df.rename(columns={"Alpha":"A"},inplace=True)

In [88]:
df['A']=df['A'].astype(float)
df

A  B  C
0  100.0  4  7
1    2.0  5  8
2    3.0  6  9

In [89]:
df.A.unique()

array([100.,   2.,   3.])

In [90]:
df['A'].value_counts()

A
100.0    1
2.0      1
3.0      1
Name: count, dtype: int64

In [91]:
df.sort_values(by='A',ascending=True)


A  B  C
1    2.0  5  8
2    3.0  6  9
0  100.0  4  7

In [92]:
df.sort_index()

A  B  C
0  100.0  4  7
1    2.0  5  8
2    3.0  6  9

In [93]:
df.groupby("A").sum()

B  C
A          
2.0    5  8
3.0    6  9
100.0  4  7

In [94]:
df.agg({"A":'sum',"B":'mean'})

A    105.0
B      5.0
dtype: float64

In [95]:
df['A'].apply(lambda x:x*2)

0    200.0
1      4.0
2      6.0
Name: A, dtype: float64

In [96]:
df.applymap(lambda x:x+2)

C:\Users\Ann\AppData\Local\Temp\ipykernel_8648\3227464113.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(lambda x:x+2)


A  B   C
0  102.0  6   9
1    4.0  7  10
2    5.0  8  11

In [97]:
# syntax, but not ideal example
df.pivot_table(values="B",index="A",aggfunc="mean")

B
A         
2.0    5.0
3.0    6.0
100.0  4.0

In [98]:
data = {
    "A":['x','y','x','y','z'],
    "B":[2,3,4,5,6]
}
pivot_df = pd.DataFrame(data)


In [99]:
pivot_df

A  B
0  x  2
1  y  3
2  x  4
3  y  5
4  z  6

In [100]:
# Best example of pivot_table
pivot_df.pivot_table(index="A",values="B",aggfunc="sum")

B
A   
x  6
y  8
z  6

In [101]:
df1 = pd.DataFrame({"A":[1,2],"B":[3,4]})
df2 = pd.DataFrame({"A":[1,2],"D":[8,9]})
pd.merge(df1,df2,on='A')

A  B  D
0  1  3  8
1  2  4  9

In [102]:
df_concat=pd.concat([df1,df2],axis=0)
df_concat

A    B    D
0  1  3.0  NaN
1  2  4.0  NaN
0  1  NaN  8.0
1  2  NaN  9.0

In [103]:
df_dict=pd.DataFrame.from_dict({"A":[1,2],"C":[12,13],"Names":["Ann","Wanjiku"]})
df_dict

A   C    Names
0  1  12      Ann
1  2  13  Wanjiku

In [104]:
df.sample(n=2)

A  B  C
0  100.0  4  7
2    3.0  6  9

In [105]:
df.duplicated()

0    False
1    False
2    False
dtype: bool

In [106]:
df.memory_usage()

Index    132
A         24
B         24
C         24
dtype: int64

In [107]:
df.T

0    1    2
A  100.0  2.0  3.0
B    4.0  5.0  6.0
C    7.0  8.0  9.0

In [108]:
df.add_prefix("col")

colA  colB  colC
0  100.0     4     7
1    2.0     5     8
2    3.0     6     9

In [109]:
df.add_suffix(".")

A.  B.  C.
0  100.0   4   7
1    2.0   5   8
2    3.0   6   9

In [110]:
# Count unique values
df.nunique()

A    3
B    3
C    3
dtype: int64

In [111]:
df['Category']=df['A'].astype("category")

In [112]:
df


A  B  C Category
0  100.0  4  7    100.0
1    2.0  5  8      2.0
2    3.0  6  9      3.0